import React, { useState } from 'react';
import { MaterialCard, CraftCategory } from '../types';
import { X, Sparkles, Loader2, Check, MessageSquare, PlusCircle } from 'lucide-react';

interface AiAssistantModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAddAiCard: (card: MaterialCard) => void;
  cards: MaterialCard[];
  highContrast: boolean;
}

export const AiAssistantModal: React.FC<AiAssistantModalProps> = ({
  isOpen,
  onClose,
  onAddAiCard,
  cards,
  highContrast,
}) => {
  const [activeTab, setActiveTab] = useState<'generate' | 'message'>('generate');

  // Generate Tab State
  const [materialName, setMaterialName] = useState('');
  const [craftType, setCraftType] = useState<CraftCategory>('sublimation');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState(false);

  // Message / NL Update Tab State
  const [aiMessage, setAiMessage] = useState('');
  const [msgLoading, setMsgLoading] = useState(false);
  const [msgError, setMsgError] = useState<string | null>(null);
  const [msgSuccess, setMsgSuccess] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!materialName.trim()) return;

    setLoading(true);
    setError(null);
    setSuccessMsg(false);

    try {
      const apiKey = localStorage.getItem('craft_diary_apikey') || '';
      const res = await fetch('/api/ai-suggest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ materialName: materialName.trim(), craftType, apiKey }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate settings from AI');
      }

      const newCard: MaterialCard = {
        id: `card-ai-${Date.now()}`,
        title: data.title || materialName.trim(),
        category: data.category || craftType,
        tags: data.tags || ['AI Generated', craftType],
        favorite: true,
        updatedAt: new Date().toISOString().split('T')[0],
        sublimation: data.sublimation || { pressure: 'Medium', timeSeconds: 60, temp: '385°F', notes: 'Generated by Gemini AI' },
        print3d: data.print3d || { headTemp: '210°C', bedTemp: '60°C', slicerProfile: 'Standard', notes: 'Generated by Gemini AI' },
        laser: data.laser || { cutSpeed: '15 mm/s', engraveModeDpi: '300 DPI', power: '75%', airAssist: true, notes: 'Generated by Gemini AI' },
        other: data.other || { disciplineName: 'General Craft', material: materialName, durationSeconds: 60, tempPressure: 'N/A', notes: 'Generated by Gemini AI' },
      };

      onAddAiCard(newCard);
      setSuccessMsg(true);
      setTimeout(() => {
        setSuccessMsg(false);
        setMaterialName('');
        onClose();
      }, 1200);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Something went wrong connecting to AI.');
    } finally {
      setLoading(false);
    }
  };

  const handleMessageSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiMessage.trim()) return;

    setMsgLoading(true);
    setMsgError(null);
    setMsgSuccess(null);

    try {
      const apiKey = localStorage.getItem('craft_diary_apikey') || '';
      const existingTitles = cards.map(c => c.title);
      const res = await fetch('/api/ai-parse-update', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: aiMessage.trim(), existingTitles, apiKey }),
      });

      const parsed = await res.json();
      if (!res.ok) {
        throw new Error(parsed.error || 'Failed to parse AI message');
      }

      // Check if matching card exists
      const targetTitle = parsed.targetTitle || 'New AI Material';
      const existingCard = cards.find(c => c.title.toLowerCase() === targetTitle.toLowerCase());

      const updatedOrNewCard: MaterialCard = {
        id: existingCard ? existingCard.id : `card-msg-${Date.now()}`,
        title: existingCard ? existingCard.title : targetTitle,
        category: parsed.category || 'sublimation',
        tags: existingCard ? existingCard.tags : ['AI Message', 'Updated'],
        favorite: true,
        updatedAt: new Date().toISOString().split('T')[0],
        sublimation: parsed.sublimation || existingCard?.sublimation || { pressure: 'Medium', timeSeconds: 60, temp: '385°F', notes: 'Updated via NL message' },
        print3d: parsed.print3d || existingCard?.print3d || { headTemp: '210°C', bedTemp: '60°C', slicerProfile: 'Standard', notes: 'Updated via NL message' },
        laser: parsed.laser || existingCard?.laser || { cutSpeed: '15 mm/s', engraveModeDpi: '300 DPI', power: '75%', airAssist: true, notes: 'Updated via NL message' },
        other: parsed.other || existingCard?.other || { disciplineName: 'General Craft', material: targetTitle, durationSeconds: 30, tempPressure: 'Standard', notes: 'Updated via NL message' },
      };

      onAddAiCard(updatedOrNewCard);
      setMsgSuccess(parsed.feedbackMessage || `Successfully ${existingCard ? 'updated' : 'created'} card "${updatedOrNewCard.title}" via AI message!`);
      setTimeout(() => {
        setMsgSuccess(null);
        setAiMessage('');
        onClose();
      }, 1600);
    } catch (err: any) {
      console.error(err);
      setMsgError(err.message || 'Failed to process AI message.');
    } finally {
      setMsgLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className={`w-full max-w-lg rounded-3xl shadow-2xl border overflow-hidden transition-all ${
        highContrast ? 'bg-zinc-900 border-zinc-700 text-white' : 'bg-amber-50 dark:bg-zinc-900 border-amber-300 text-amber-950 dark:text-amber-100'
      }`}>
        
        {/* Header */}
        <div className={`px-6 py-4 border-b flex items-center justify-between ${
          highContrast ? 'border-zinc-800 bg-zinc-950' : 'border-amber-200 bg-amber-100 dark:bg-zinc-900 dark:border-zinc-800'
        }`}>
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600" />
            <h2 className="font-serif font-bold text-xl">Gemini AI Craft Assistant</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-amber-200 dark:hover:bg-zinc-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tabs Bar */}
        <div className="grid grid-cols-2 p-2 bg-amber-100/60 dark:bg-zinc-950 border-b border-amber-200 dark:border-zinc-800 gap-2">
          <button
            onClick={() => setActiveTab('generate')}
            className={`flex items-center justify-center gap-2 py-2 px-3 rounded-xl text-xs font-bold transition ${
              activeTab === 'generate'
                ? 'bg-purple-600 text-white shadow'
                : 'bg-white/70 dark:bg-zinc-900 text-purple-900 dark:text-purple-300 hover:bg-white'
            }`}
          >
            <PlusCircle className="w-4 h-4" />
            <span>Generate Card Wizard</span>
          </button>
          <button
            onClick={() => setActiveTab('message')}
            className={`flex items-center justify-center gap-2 py-2 px-3 rounded-xl text-xs font-bold transition ${
              activeTab === 'message'
                ? 'bg-purple-600 text-white shadow'
                : 'bg-white/70 dark:bg-zinc-900 text-purple-900 dark:text-purple-300 hover:bg-white'
            }`}
          >
            <MessageSquare className="w-4 h-4" />
            <span>AI Message & Update</span>
          </button>
        </div>

        {/* Tab 1: Generate Card Wizard */}
        {activeTab === 'generate' && (
          <form onSubmit={handleGenerate} className="p-6 space-y-4">
            <p className="text-xs opacity-80 leading-relaxed">
              Enter any new material, blank, or fabric name below. Gemini AI will instantly calculate and format the optimal Sublimation, 3D Printing, and Laser Cutter parameters for your workshop diary!
            </p>

            <div>
              <label className="block text-xs font-semibold mb-1">Material / Blank Name *</label>
              <input
                type="text"
                required
                value={materialName}
                onChange={(e) => setMaterialName(e.target.value)}
                placeholder="e.g. Glass Cutting Board 8x11"
                className={`w-full px-3.5 py-2.5 rounded-xl text-sm border outline-none ${
                  highContrast ? 'bg-zinc-950 border-zinc-750 text-white' : 'bg-white dark:bg-zinc-800 border-amber-300 dark:border-zinc-700'
                }`}
              />
            </div>

            <div>
              <label className="block text-xs font-semibold mb-1">Primary Craft Focus</label>
              <select
                value={craftType}
                onChange={(e) => setCraftType(e.target.value as CraftCategory)}
                className={`w-full px-3.5 py-2.5 rounded-xl text-sm border outline-none ${
                  highContrast ? 'bg-zinc-950 border-zinc-750 text-white' : 'bg-white dark:bg-zinc-800 border-amber-300 dark:border-zinc-700'
                }`}
              >
                <option value="sublimation">Sublimation</option>
                <option value="3d_printing">3D Printing</option>
                <option value="laser_cutter">Laser Cutter</option>
                <option value="other">Miscellaneous / Other</option>
              </select>
            </div>

            {error && (
              <div className="p-3 rounded-xl bg-red-100 dark:bg-red-950/60 border border-red-300 text-red-700 dark:text-red-300 text-xs font-medium">
                {error}
              </div>
            )}

            {successMsg && (
              <div className="p-3 rounded-xl bg-green-100 dark:bg-green-950/60 border border-green-300 text-green-700 dark:text-green-300 text-xs font-medium flex items-center gap-2">
                <Check className="w-4 h-4" />
                <span>AI successfully generated and added new card to your Rolodex!</span>
              </div>
            )}

            <div className="pt-2 flex items-center justify-end gap-3">
              <button
                type="button"
                onClick={onClose}
                className="px-5 py-2.5 rounded-xl text-xs font-bold border border-amber-300 dark:border-zinc-700 hover:bg-amber-100 dark:hover:bg-zinc-800 transition"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading || !materialName.trim()}
                className="flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs font-bold bg-gradient-to-r from-purple-600 to-indigo-600 text-white shadow hover:opacity-95 transition disabled:opacity-50"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>Consulting Gemini AI...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 text-purple-200" />
                    <span>Generate Settings</span>
                  </>
                )}
              </button>
            </div>
          </form>
        )}

        {/* Tab 2: AI Message & Update Assistant */}
        {activeTab === 'message' && (
          <form onSubmit={handleMessageSubmit} className="p-6 space-y-4">
            <p className="text-xs opacity-80 leading-relaxed">
              Message your assistant in natural language (simulating an on-device model like Gemma 3 1B) to update or create craft settings instantly!
            </p>

            <div>
              <label className="block text-xs font-semibold mb-1">Natural Language Instruction *</label>
              <textarea
                rows={3}
                required
                value={aiMessage}
                onChange={(e) => setAiMessage(e.target.value)}
                placeholder="e.g. Update material Baltic Birch Plywood to cut speed 20 mm/s and power 90%"
                className={`w-full px-3.5 py-2.5 rounded-xl text-sm border outline-none ${
                  highContrast ? 'bg-zinc-950 border-zinc-750 text-white' : 'bg-white dark:bg-zinc-800 border-amber-300 dark:border-zinc-700'
                }`}
              />
            </div>

            {msgError && (
              <div className="p-3 rounded-xl bg-red-100 dark:bg-red-950/60 border border-red-300 text-red-700 dark:text-red-300 text-xs font-medium">
                {msgError}
              </div>
            )}

            {msgSuccess && (
              <div className="p-3 rounded-xl bg-green-100 dark:bg-green-950/60 border border-green-300 text-green-700 dark:text-green-300 text-xs font-medium flex items-center gap-2">
                <Check className="w-4 h-4" />
                <span>{msgSuccess}</span>
              </div>
            )}

            <div className="pt-2 flex items-center justify-end gap-3">
              <button
                type="button"
                onClick={onClose}
                className="px-5 py-2.5 rounded-xl text-xs font-bold border border-amber-300 dark:border-zinc-700 hover:bg-amber-100 dark:hover:bg-zinc-800 transition"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={msgLoading || !aiMessage.trim()}
                className="flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs font-bold bg-gradient-to-r from-purple-600 to-indigo-600 text-white shadow hover:opacity-95 transition disabled:opacity-50"
              >
                {msgLoading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>Parsing AI Message...</span>
                  </>
                ) : (
                  <>
                    <MessageSquare className="w-4 h-4 text-purple-200" />
                    <span>Send Message & Update</span>
                  </>
                )}
              </button>
            </div>
          </form>
        )}

      </div>
    </div>
  );
};
